#!/bin/bash

SSHD_PATH=/etc/ssh/sshd_config
PASS_CHECK=$(echo $pass | checklib-test)

if [ "$EUID" -ne 0 ]; then
	echo "You must run this as root"
	exit 1
fi

function u_requirements(){
	sudo apt install cracklib-runtime
}

function sudo_user_create(){
	read -r -p "Name of the Sudo User (this user will be the one with witch you connect to the server, root access will be disable for security): " key
	read -r -p "Password for $key (must be strong): " pass
	if [[$PASS_CHECK = "$pass: OK"]]; then
		useradd $key -m -p $pass -g sudo -s /bin/sh
	else
		echo "[-] Your password is too simple"
		sudo_user_create
	fi
}
function u_ssh(){
	sed -i -e 's/#PermitRootLogin yes/PermitRootLogin no/g'
	sed -i -e 's/#Port 22/Port 69/g'
	sed -i -e 's/#Banner none/Banner /etc/issue/g'
	sed -i -e 's/PasswordAuthentification yes/PasswordAuthentification no/g'
}

function Ubuntu(){
	sudo_user_create
	u_ssh
}

if [ "$1" = "-ubuntu" ]; then
	Ubuntu
