#!/bin/bash

SSHD_PATH=/etc/ssh/sshd_config
PASS_CHECK=$(echo $pass | checklib-test)

if [ "$EUID" -ne 0 ]; then
	echo "You must run this as root"
	exit 1
fi

function sudo_user_create(){
	read -r -p "Name of the Sudo User (this user will be the one with witch you connect to the server, root access will be disable for security): " key
	read -r -p "Password for $key (must be strong): " pass
	if [[$PASS_CHECK = "$pass: OK"]]; then
		useradd $key -m -p $pass -aG wheel -s /bin/sh
		echo "[+] user $key has been created you must do the folowing :"
		echo "Put your SSH key in /home/$key/.ssh/authorised_keys"
		echo "If you don't know what an ssh key is check this: "
		sleep 5
	else
		echo "[-] Your password is too simple"
		sudo_user_create
	fi
}
function ssh(){
	sed -i -e 's/#PermitRootLogin yes/PermitRootLogin no/g'
	sed -i -e 's/#Port 22/Port 69/g'
	sed -i -e 's/#Banner none/Banner /etc/issue/g'
	sed -i -e 's/PasswordAuthentification yes/PasswordAuthentification no/g'
}

function Firewall()
{
	systemctl enable --now firewalld
	systemctl start firewalld
	read -r -p "[*] List the services you wish to enable (https ssh ftp etc..): " key
	read -r -p "[*] List the ports you wish to open: " key2
	for i in $key; do
		firewall-cmd --permanent --zone=public --add-service=$i
	done
	for i in $key2; do
		firewall-cmd --permanent --zone=public --add-port=$i
	done
	firewall-cmd --reload
	echo "[+] Firewalld has been setup"
}
if [ "$1" = "-firewall" ]; then
	Firewall
elif [ "$1" = "--help" ]; then
	echo "No help page yet"
else
	echo "Error invalid arguments"
	echo "try --help"
fi
